### ISSUE TITLE
Corrupt/Malformed Pretrain Weights

### ISSUE THREAD

**Issue by amanikiruga** [cvlab-columbia/oops#6]
This is an amazing paper and great thanks for sharing the code. 
I downloaded the pretrain weights from your website here: [Oops Models](https://oops.cs.columbia.edu/data/)
However, one of the models oops_model.pth can't be deserialized with torch.load() Attached is the screenshot. 
Why is this the case? 

![image](https://user-images.githubusercontent.com/69642575/124197784-4fe41380-da9d-11eb-8b5c-f23b57a316f4.png)

**Comment by dave-epstein** [comment]
Hi Amani, you might have a corrupted download. I just tried to download the weights from the dataset page and I was able to load them into memory without any issues.

**Comment by amanikiruga** [comment]
You are right, it was a corrupt download. 😃
So is it correct that the difference between fps_model and oops_model is that the former is just the learned representation and oops_model is that plus the trained linear classifier?
Kind regards, 

Amani K.

**Comment by dave-epstein** [comment]
I believe the fps_model is fine-tuned, so the weights of the entire model are trained on the Oops task (incl. linear layer).
