### ISSUE TITLE
Can't replicate results

### ISSUE THREAD

**Issue by amanikiruga** [cvlab-columbia/oops#7]
Hey Dave, 

I am trying to run inference using either fps_model or oops_model pretrain weights. All I am trying to do is benchmark the oops classification task to see it working. However, I am getting weird results which make me think I am doing something wrong. 
Just to test inference, I use VideoClips class from torchvision.datasets.video_utils (torchvision backend is video_reader) and create a dataset that inherits from VisionDataset as follows: 
I am running this on Google Colab on a P100 GPU, torchvision 0.8.0+cu110, torch 1.7.1+cu110
```python
class TestDataset(VisionDataset): 
  def __init__(self, video_path): 
    assert video_path is not None 
    self.video_path = video_path
    self.video_clips = VideoClips([video_path]) #just one video
   # self.video_clips.compute_clips(16, 1) 
    
  def __len__(self): 
    return self.video_clips.num_clips()
  def __getitem__(self, idx): 
    video, *_ = self.video_clips.get_clip(idx)
    return video

test_dataset = TestDataset(test_path)

testdl = data.DataLoader(
        dataset=test_dataset,
        batch_size=1, 
        shuffle = False,
        pin_memory=True, 
        drop_last=False)
```
I then run this inference loop: 

```python

model.to(device) 
thresh = 0.5
test_preds = []
for idx, xs in enumerate(testdl):
  model.eval()
  xs = xs.permute(0, 4, 1, 2, 3).float().to(device)
  with torch.no_grad(): 
    y_hats = model(xs)
    print(y_hats)
  pred = F.softmax(y_hats, dim = 1).argmax().item()
  print(pred) 
  test_preds.append(pred)
```
However, with fps_model, and one of the fail vids,  pred is always ``2`` for all frames.
Is there something wrong I am doing? 
[video used](https://cv.cs.columbia.edu/dave/fails/viz_gif/scenes_padded/val/Classic%20bails%20and%20Throwback%20Fails%20(June%202017)%20_%20FailArmy40.mp4):

**Comment by dave-epstein** [comment]
What is your data preprocessing pipeline? Make sure to use the exact transform expected by our model.

**Comment by amanikiruga** [comment]
Once again, you are correct! Silly of me not to have transformed the same way. Thanks for taking the time to reply.
